### ISSUE TITLE
Useless constraint

### ISSUE THREAD

**Issue by tripulse** [Motzumoto/DiscordClearDms#2]
https://github.com/Motzumoto/DiscordClearDms/blob/1f3d7cd416842af1ff2ba45e2fa38d53d4677573/clscript.py#L49

What is the point of hardcoded limit of `9999` messages? Is this to avoid rate-limiting?

**Comment by Motzumoto** [comment]
holy shit, i didnt see this issue until now, and yes, its to prevent rate-limiting. you can remove the limit if you want, but i cant guarantee if your account will be safe without it
